library(ISLR)
data(Default)
head(Default)
library(caret)
set.seed(2016)
levels(Default$default) <- make.names(levels(factor(Default$default)))
Default$default <- relevel(Default$default, "Yes")
inTrain <- createDataPartition(Default$default, p=0.7, list = F)
train <- Default[inTrain,]
test <- Default[-inTrain,]
upSampTrain <- upSample(x = train[,2:4], y = train$default,yname = "default")
downSampTrain <- downSample(x = train[,2:4], y = train$default,yname = "default")
table(train$default)
table(upSampTrain$default)
table(downSampTrain$default)
ctrl <- trainControl(method = "cv", classProbs = TRUE, summaryFunction = twoClassSummary)
logit <- train(default ~ ., data = train, method = "glm", family = "binomial", trControl = ctrl, metric = "ROC")
uplogit <- train(default ~ ., data = upSampTrain, method = "glm", family = "binomial", trControl = ctrl, metric = "ROC")
downlogit <- train(default ~ ., data = downSampTrain, method = "glm", family = "binomial", trControl = ctrl, metric = "ROC")
summary(logit)
summary(downlogit)
summary(uplogit)
ldaFit <- train(default ~ ., data = train, method = "lda", trControl = ctrl, metric = "ROC")
upldaFit <- train(default ~ ., data = upSampTrain, method = "lda", trControl = ctrl, metric = "ROC")
downldaFit <- train(default ~ ., data = downSampTrain, method = "lda",trControl = ctrl, metric = "ROC")
qdaFit <- train(default ~ ., data = train, method = "qda", trControl = ctrl, metric = "ROC")
upqdaFit <- train(default ~ ., data = upSampTrain, method = "qda", trControl = ctrl, metric = "ROC")
downqdaFit <- train(default ~ ., data = downSampTrain, method = "qda",trControl = ctrl, metric = "ROC")
logitProbs <- predict(logit, newdata = test, type = "prob")[,1]
uplogitProbs <- predict(uplogit, newdata = test, type = "prob")[,1]
downlogitProbs <- predict(downlogit, newdata = test, type = "prob")[,1]
ldaProbs <- predict(ldaFit, newdata = test, type = "prob")[,1]
upldaProbs <- predict(upldaFit, newdata = test, type = "prob")[,1]
downldaProbs <- predict(downldaFit, newdata = test, type = "prob")[,1]
qdaProbs <- predict(qdaFit, newdata = test, type = "prob")[,1]
upqdaProbs <- predict(upqdaFit, newdata = test, type = "prob")[,1]
downqdaProbs <- predict(downqdaFit, newdata = test, type = "prob")[,1]
ldaClasses <- predict(ldaFit, newdata = test)
upldaClasses <- predict(upldaFit, newdata = test)
downldaClasses <- predict(downldaFit, newdata = test)
qdaClasses <- predict(qdaFit, newdata = test)
upqdaClasses <- predict(upqdaFit, newdata = test)
downqdaClasses <- predict(downqdaFit, newdata = test)
logitClasses <- predict(logit, newdata = test)
uplogitClasses <- predict(uplogit, newdata = test)
downlogitClasses <- predict(downlogit, newdata = test)
confusionMatrix(data = ldaClasses, test$default)
confusionMatrix(data = upldaClasses, test$default)
confusionMatrix(data = downldaClasses, test$default)
confusionMatrix(data = qdaClasses, test$default)
confusionMatrix(data = upqdaClasses, test$default)
confusionMatrix(data = downqdaClasses, test$default)
confusionMatrix(data = logitClasses, test$default)
confusionMatrix(data = uplogitClasses, test$default)
confusionMatrix(data = downlogitClasses, test$default)
library(pROC)
rocCurve <- roc(response = test$default, predictor = logitProbs, levels = rev(levels(test$default)))
uprocCurve <- roc(response = test$default, predictor = uplogitProbs, levels = rev(levels(test$default)))
downrocCurve <- roc(response = test$default, predictor = downlogitProbs, levels = rev(levels(test$default)))
ldaCurve <- roc(response = test$default, predictor = ldaProbs, levels = rev(levels(test$default)))
upldaCurve <- roc(response = test$default, predictor = upldaProbs, levels = rev(levels(test$default)))
downldaCurve <- roc(response = test$default, predictor = downldaProbs, levels = rev(levels(test$default)))
qdaCurve <- roc(response = test$default, predictor = qdaProbs, levels = rev(levels(test$default)))
upqdaCurve <- roc(response = test$default, predictor = upqdaProbs, levels = rev(levels(test$default)))
downqdaCurve <- roc(response = test$default, predictor = downqdaProbs, levels = rev(levels(test$default)))
par(mfrow=c(1,1)) # reset graphics parameter to 1 plot
plot(rocCurve, legacy.axes=T, col="dark red"
     , main="Receiver Operating Characteristic (ROC) Curve")
lines(uprocCurve, col="orange")
lines(uprocCurve, col="pink")
lines(ldaCurve, col="light green")
lines(upldaCurve, col="dark green")
lines(downldaCurve, col="darkolivegreen")
lines(qdaCurve, col="light blue")
lines(upqdaCurve, col="dark blue")
lines(downqdaCurve, col="black")
legend("bottomright", inset=0, title="Model", border="white", bty="n", cex=.8
       , legend=c("Logit","UpLogit","DownLogit","LDA","upLDA","downLDA","QDA", "UpQDA", "DownQDA")
       , fill=c("dark red","orange","pink","light green","dark green","darkolivegreen","light blue","dark blue","black"))